### ISSUE TITLE
There are not any 'ori_pqaa.json' dataset file

### ISSUE THREAD

**Issue by minstar** [pubmedqa/pubmedqa#2]
Hi, I am really interested in this pubmedQA dataset.
I was trying to produce a dataset with split code.
However, there isn't any 'ori_pqaa.json' file.
Can you please upload this?

**Comment by drqiaojin** [comment]
Hi @minstar, thanks for your interest!

You can download PQA-A here: https://github.com/pubmedqa/pubmedqa#download.

Qiao

**Comment by minstar** [comment]
Thank you very much!
