### ISSUE TITLE
PQA-L vs PQA-A vs PQA-U?

### ISSUE THREAD

**Issue by johntiger1** [pubmedqa/pubmedqa#3]
Just to confirm, L = Label, A = artificially generated and U = unlabelled? 

Where did you get the "LONG ANSWER" from for PQA-U? It says from the paper that you used the Conclusion section, but was there any verification or analysis for justifying this decision?

Thanks

**Comment by drqiaojin** [comment]
Hi @johntiger1, thank you for being interested in our work.

> Just to confirm, L = Label, A = artificially generated and U = unlabelled?

That's right.

> Where did you get the "LONG ANSWER" from for PQA-U? It says from the paper that you used the Conclusion section, but was there any verification or analysis for justifying this decision?

We obtain the "LONG ANSWER" from the "Conclusion(s)" sections of structured abstracts. It's assumed that authors should answer their question in the title when writing conclusions in the abstract. We did find it much easier and more precise to annotate yes/no/maybe with the conclusions than without (you can check the human performance under different settings). However, there is no well-designed verification.

**Comment by johntiger1** [comment]
Thank you, that makes sense!
